"""Sequential fiscal--monetary stress simulation.

This module closes the first causal loop that the path-based experiments leave
open.  Treasury accounting, macro feedback, and the policy reaction advance one
quarter at a time, so interest generated by the stressed debt stock can affect
later demand, inflation, and policy rates.

The engine never targets a terminal debt ratio or solves for an inflation path.
It preserves a parallel no-shock ledger so only incremental interest created by
the stress enters the new interest-income demand channel.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from debt_sim.debt_stock import DebtStock, IssuanceStrategy
from debt_sim.economy import advance_gdp, annualized_flow_gdp_share
from debt_sim.model import run_simulation, validate_assumptions
from debt_sim.policy import PathInput, PolicyRegime, PolicyRule


@dataclass(frozen=True, slots=True)
class InterestIncomeRule:
    """Allocation and spending of incremental cash interest.

    Recipient shares describe the holders of debt represented by the cohort
    ledger.  Spending fractions describe the share of an incremental quarterly
    interest payment that becomes demand for domestically produced goods and
    services.  These are scenario parameters until calibrated.
    """

    domestic_private_share: float = 0.60
    foreign_share: float = 0.25
    federal_reserve_share: float = 0.15
    domestic_private_spending_fraction: float = 0.25
    foreign_domestic_spending_fraction: float = 0.05
    federal_reserve_spending_fraction: float = 0.0

    def __post_init__(self) -> None:
        shares = (
            self.domestic_private_share,
            self.foreign_share,
            self.federal_reserve_share,
        )
        spending = (
            self.domestic_private_spending_fraction,
            self.foreign_domestic_spending_fraction,
            self.federal_reserve_spending_fraction,
        )
        if any(not 0.0 <= value <= 1.0 for value in (*shares, *spending)):
            raise ValueError("interest-recipient shares and spending fractions must be in [0, 1]")
        if not np.isclose(sum(shares), 1.0, atol=1e-9):
            raise ValueError("interest-recipient shares must sum to one")

    @property
    def domestic_demand_fraction(self) -> float:
        """Fraction of incremental cash interest entering domestic demand."""

        return (
            self.domestic_private_share * self.domestic_private_spending_fraction
            + self.foreign_share * self.foreign_domestic_spending_fraction
            + self.federal_reserve_share * self.federal_reserve_spending_fraction
        )

    def domestic_demand_billions(self, incremental_cash_interest_billions: float) -> float:
        return incremental_cash_interest_billions * self.domestic_demand_fraction


@dataclass(frozen=True, slots=True)
class SequentialFeedbackRule:
    """Visible quarterly macro-fiscal transmission coefficients."""

    output_gap_persistence: float = 0.80
    policy_tightening_output_semi_elasticity: float = 0.25
    private_credit_spread_output_semi_elasticity: float = 0.15
    primary_deficit_output_multiplier: float = 0.80
    interest_income_output_multiplier: float = 1.00
    policy_effect_lag_quarters: int = 2
    fiscal_effect_lag_quarters: int = 1
    inflation_persistence: float = 0.98
    inflation_output_gap_sensitivity: float = 0.06
    inflation_gap_lag_quarters: int = 2
    automatic_stabilizer_semi_elasticity: float = 0.45
    primary_deficit_scales_with_nominal_gdp: bool = True

    def __post_init__(self) -> None:
        if not 0.0 <= self.output_gap_persistence < 1.0:
            raise ValueError("output-gap persistence must be in [0, 1)")
        if not 0.0 <= self.inflation_persistence <= 1.0:
            raise ValueError("inflation persistence must be in [0, 1]")
        coefficients = (
            self.policy_tightening_output_semi_elasticity,
            self.private_credit_spread_output_semi_elasticity,
            self.primary_deficit_output_multiplier,
            self.interest_income_output_multiplier,
            self.inflation_output_gap_sensitivity,
            self.automatic_stabilizer_semi_elasticity,
        )
        if min(coefficients) < 0.0:
            raise ValueError("feedback coefficients cannot be negative")
        if (
            min(
                self.policy_effect_lag_quarters,
                self.fiscal_effect_lag_quarters,
                self.inflation_gap_lag_quarters,
            )
            < 1
        ):
            raise ValueError("feedback lags must be at least one quarter")


@dataclass(frozen=True, slots=True)
class DebtYieldFeedbackRule:
    """Map a lagged debt-ratio deterioration into Treasury issuance yields.

    The signal is the scenario debt/GDP ratio minus the parallel reference
    ratio, measured in percentage points. Coefficients are basis points of
    additional yield per percentage point of that gap. A reference-relative
    signal avoids adding the baseline debt effect a second time.

    The central coefficients are a transparent interpretation of Bhatt et al.
    (2026): 1--2 basis points in longer-run neutral rates and 2--3 basis points
    in the ten-year term premium per percentage point of expected debt/GDP.
    Their expected-debt estimate does not identify this model's lag structure,
    maturity mapping, or crisis nonlinearities, so all remain sensitivity
    parameters.
    """

    short_basis_points_per_debt_gdp_percentage_point: float = 0.0
    intermediate_basis_points_per_debt_gdp_percentage_point: float = 1.5
    long_basis_points_per_debt_gdp_percentage_point: float = 4.0
    tips_real_basis_points_per_debt_gdp_percentage_point: float = 1.5
    signal_lag_quarters: int = 1
    apply_only_to_positive_debt_gap: bool = True

    def __post_init__(self) -> None:
        coefficients = (
            self.short_basis_points_per_debt_gdp_percentage_point,
            self.intermediate_basis_points_per_debt_gdp_percentage_point,
            self.long_basis_points_per_debt_gdp_percentage_point,
            self.tips_real_basis_points_per_debt_gdp_percentage_point,
        )
        if min(coefficients) < 0.0:
            raise ValueError("debt-yield feedback coefficients cannot be negative")
        if self.signal_lag_quarters < 1:
            raise ValueError("debt-yield feedback lag must be at least one quarter")

    def yield_adjustments_basis_points(self, debt_gdp_gap: float) -> dict[str, float]:
        """Return maturity-specific yield adjustments for one debt signal."""

        signal = max(debt_gdp_gap, 0.0) if self.apply_only_to_positive_debt_gap else debt_gdp_gap
        return {
            "short": signal * self.short_basis_points_per_debt_gdp_percentage_point,
            "intermediate": (
                signal * self.intermediate_basis_points_per_debt_gdp_percentage_point
            ),
            "long": signal * self.long_basis_points_per_debt_gdp_percentage_point,
            "tips": signal * self.tips_real_basis_points_per_debt_gdp_percentage_point,
        }


@dataclass(frozen=True, slots=True)
class PrivateAbsorptionRule:
    """Reference-anchored, finite private Treasury absorption diagnostic.

    The reference path is assigned a capacity multiple of one. Higher nominal
    yields expand capacity at the configured rate until the finite maximum is
    reached. This is a transparent sensitivity rule, not an estimated demand
    curve.
    """

    capacity_increase_fraction_per_100_basis_points: float = 0.05
    maximum_capacity_multiple: float = 1.50
    minimum_capacity_multiple: float = 0.0

    def __post_init__(self) -> None:
        if self.capacity_increase_fraction_per_100_basis_points < 0.0:
            raise ValueError("private-absorption yield sensitivity cannot be negative")
        if not 0.0 <= self.minimum_capacity_multiple <= 1.0:
            raise ValueError("minimum private-absorption capacity multiple must be in [0, 1]")
        if self.maximum_capacity_multiple < 1.0:
            raise ValueError("maximum private-absorption capacity multiple must be at least one")
        if self.maximum_capacity_multiple < self.minimum_capacity_multiple:
            raise ValueError("maximum capacity cannot be below minimum capacity")


class PrivateFinancingCapacityError(ValueError):
    """Raised when no supported yield can place the quarter's gross issuance."""

    def __init__(
        self,
        *,
        quarter: str,
        required_capacity_multiple: float,
        maximum_capacity_multiple: float,
        required_gross_issuance_billions: float,
        maximum_capacity_billions: float,
        reason: str = "finite_capacity_exceeded",
    ) -> None:
        self.quarter = quarter
        self.required_capacity_multiple = required_capacity_multiple
        self.maximum_capacity_multiple = maximum_capacity_multiple
        self.required_gross_issuance_billions = required_gross_issuance_billions
        self.maximum_capacity_billions = maximum_capacity_billions
        self.reason = reason
        super().__init__(
            f"private financing capacity failed in {quarter}: required "
            f"{required_capacity_multiple:.3f} times reference issuance, above the "
            f"supported {maximum_capacity_multiple:.3f} multiple ({reason})"
        )


@dataclass(frozen=True, slots=True)
class SequentialCrisisResult:
    """Quarterly stressed path and its parallel no-shock reference path."""

    quarterly: pd.DataFrame
    reference_quarterly: pd.DataFrame
    ending_stock: DebtStock
    reference_ending_stock: DebtStock
    scenario_name: str
    data_vintage: str


def _numeric_path(index: pd.PeriodIndex, value: PathInput, name: str) -> pd.Series:
    if isinstance(value, pd.Series):
        result = value.reindex(index).astype(float)
        if result.isna().any():
            raise ValueError(f"{name} must specify every simulated quarter")
    else:
        result = pd.Series(float(value), index=index, dtype=float)
    if not np.isfinite(result.to_numpy()).all():
        raise ValueError(f"{name} contains non-finite values")
    return result


def _actual_real_growth(
    reference_growth: float, output_gap: float, prior_output_gap: float
) -> float:
    if min(1.0 + output_gap, 1.0 + prior_output_gap) <= 0.0:
        raise ValueError("output gap reached the model boundary at -100 percent")
    reference_quarterly_factor = (1.0 + reference_growth) ** 0.25
    actual_quarterly_factor = (
        reference_quarterly_factor * (1.0 + output_gap) / (1.0 + prior_output_gap)
    )
    if actual_quarterly_factor <= 0.0:
        raise ValueError("calculated real-GDP growth reached the model boundary")
    return actual_quarterly_factor**4 - 1.0


def _cash_interest(row: pd.Series) -> float:
    """Cash interest available to recipients, excluding TIPS principal indexation."""

    return float(
        row["marketable_interest_excluding_tips_inflation_billions"]
        + row["other_public_debt_interest_billions"]
        + row["tips_deflation_floor_cost_billions"]
    )


def _nominal_issuance_yield_proxy(path: pd.DataFrame) -> pd.Series:
    bill_weight = path["new_borrowing_bill_share"]
    note_weight = path["new_borrowing_note_share"]
    bond_weight = path["new_borrowing_bond_share"]
    frn_weight = path["new_borrowing_frn_share"]
    nominal_weight = bill_weight + note_weight + bond_weight + frn_weight
    weighted_rate = (
        (bill_weight + frn_weight) * path["short_issuance_rate"]
        + note_weight * path["intermediate_issuance_rate"]
        + bond_weight * path["long_issuance_rate"]
    )
    return weighted_rate / nominal_weight.replace(0.0, np.nan)


def _private_absorption_state(
    stress_output: pd.Series,
    reference_output: pd.Series,
    rule: PrivateAbsorptionRule,
) -> dict[str, float | bool]:
    stress = pd.DataFrame([stress_output])
    reference = pd.DataFrame([reference_output])
    stress_yield = float(_nominal_issuance_yield_proxy(stress).iloc[0])
    reference_yield = float(_nominal_issuance_yield_proxy(reference).iloc[0])
    reference_scaled_issuance = float(
        reference_output["gross_treasury_issuance_billions"]
        * stress_output["nominal_gdp_billions_saar"]
        / reference_output["nominal_gdp_billions_saar"]
    )
    required_issuance = float(stress_output["gross_treasury_issuance_billions"])
    required_capacity_multiple = (
        required_issuance / reference_scaled_issuance
        if reference_scaled_issuance > 0.0
        else np.inf
    )
    yield_gap_basis_points = (stress_yield - reference_yield) * 10_000.0
    unconstrained_capacity_multiple = (
        1.0
        + rule.capacity_increase_fraction_per_100_basis_points
        * yield_gap_basis_points
        / 100.0
    )
    capacity_multiple = min(
        max(unconstrained_capacity_multiple, rule.minimum_capacity_multiple),
        rule.maximum_capacity_multiple,
    )
    if rule.capacity_increase_fraction_per_100_basis_points > 0.0:
        required_yield_gap_basis_points = (
            max(required_capacity_multiple - 1.0, 0.0)
            / rule.capacity_increase_fraction_per_100_basis_points
            * 100.0
        )
    else:
        required_yield_gap_basis_points = np.inf
    return {
        "reference_scaled_issuance_billions": reference_scaled_issuance,
        "required_gross_issuance_billions": required_issuance,
        "required_capacity_multiple": required_capacity_multiple,
        "yield_gap_basis_points": yield_gap_basis_points,
        "capacity_multiple_at_actual_yield": capacity_multiple,
        "capacity_billions_at_actual_yield": reference_scaled_issuance * capacity_multiple,
        "required_yield_gap_basis_points": required_yield_gap_basis_points,
        "finite_capacity_exceeded": (
            required_capacity_multiple > rule.maximum_capacity_multiple + 1e-12
        ),
    }


def build_private_absorption_diagnostics(
    result: SequentialCrisisResult,
    rule: PrivateAbsorptionRule | None = None,
) -> pd.DataFrame:
    """Compare required gross issuance with a finite private-capacity rule."""

    absorption = rule or PrivateAbsorptionRule()
    stress = result.quarterly.reset_index(drop=True)
    reference = result.reference_quarterly.reset_index(drop=True)
    if len(stress) != len(reference):
        raise ValueError("stress and reference paths must have the same length")

    stress_yield = _nominal_issuance_yield_proxy(stress)
    reference_yield = _nominal_issuance_yield_proxy(reference)
    yield_gap_basis_points = (stress_yield - reference_yield) * 10_000.0
    reference_scaled_issuance = (
        reference["gross_treasury_issuance_billions"]
        * stress["nominal_gdp_billions_saar"]
        / reference["nominal_gdp_billions_saar"]
    )
    required_issuance = stress["gross_treasury_issuance_billions"]
    required_capacity_multiple = required_issuance / reference_scaled_issuance.replace(0.0, np.nan)
    unconstrained_capacity_multiple = (
        1.0
        + absorption.capacity_increase_fraction_per_100_basis_points
        * yield_gap_basis_points
        / 100.0
    )
    capacity_multiple = unconstrained_capacity_multiple.clip(
        lower=absorption.minimum_capacity_multiple,
        upper=absorption.maximum_capacity_multiple,
    )
    capacity = reference_scaled_issuance * capacity_multiple
    shortfall = (required_issuance - capacity).clip(lower=0.0)
    finite_capacity_exceeded = (
        required_capacity_multiple > absorption.maximum_capacity_multiple + 1e-12
    )
    if absorption.capacity_increase_fraction_per_100_basis_points > 0.0:
        required_yield_gap = (
            (required_capacity_multiple - 1.0).clip(lower=0.0)
            / absorption.capacity_increase_fraction_per_100_basis_points
            * 100.0
        )
    else:
        required_yield_gap = pd.Series(np.nan, index=stress.index, dtype=float)

    return pd.DataFrame(
        {
            "quarter": stress["quarter"],
            "reference_gross_issuance_billions": reference["gross_treasury_issuance_billions"],
            "reference_scaled_gross_issuance_billions": reference_scaled_issuance,
            "required_gross_issuance_billions": required_issuance,
            "stress_nominal_issuance_yield_proxy": stress_yield,
            "reference_nominal_issuance_yield_proxy": reference_yield,
            "nominal_issuance_yield_gap_basis_points": yield_gap_basis_points,
            "required_private_capacity_multiple": required_capacity_multiple,
            "private_absorption_capacity_multiple_at_actual_yield": capacity_multiple,
            "private_absorption_capacity_billions_at_actual_yield": capacity,
            "private_absorption_shortfall_billions_at_actual_yield": shortfall,
            "required_yield_gap_basis_points_without_capacity_limit": required_yield_gap,
            "required_short_yield_without_capacity_limit": (
                reference["short_issuance_rate"] + required_yield_gap / 10_000.0
            ),
            "finite_private_absorption_capacity_exceeded": finite_capacity_exceeded,
            "maximum_private_absorption_capacity_multiple": (absorption.maximum_capacity_multiple),
        }
    )


def summarize_private_absorption(diagnostics: pd.DataFrame) -> dict[str, float | str | bool]:
    """Summarize the first financing constraints under a supplied capacity rule."""

    shortfall = diagnostics.loc[
        diagnostics["private_absorption_shortfall_billions_at_actual_yield"] > 1e-9,
        "quarter",
    ]
    finite = diagnostics.loc[
        diagnostics["finite_private_absorption_capacity_exceeded"],
        "quarter",
    ]
    return {
        "private_absorption_shortfall_occurs": not shortfall.empty,
        "first_private_absorption_shortfall": "" if shortfall.empty else str(shortfall.iloc[0]),
        "finite_private_absorption_capacity_exceeded": not finite.empty,
        "first_finite_private_absorption_capacity_exceeded": (
            "" if finite.empty else str(finite.iloc[0])
        ),
        "peak_required_private_capacity_multiple": float(
            diagnostics["required_private_capacity_multiple"].max()
        ),
        "peak_private_absorption_shortfall_billions": float(
            diagnostics["private_absorption_shortfall_billions_at_actual_yield"].max()
        ),
        "cumulative_private_absorption_shortfall_billions": float(
            diagnostics["private_absorption_shortfall_billions_at_actual_yield"].sum()
        ),
        "peak_required_short_yield_without_capacity_limit": float(
            diagnostics["required_short_yield_without_capacity_limit"].max()
        ),
    }


def _first_sustained_breach(
    periods: pd.Series,
    values: pd.Series,
    ceiling: float,
    sustained_quarters: int,
) -> str:
    run_length = 0
    for position, value in enumerate(values):
        run_length = run_length + 1 if float(value) > ceiling else 0
        if run_length >= sustained_quarters:
            return str(periods.iloc[position - sustained_quarters + 1])
    return ""


def summarize_crisis_path(
    result: SequentialCrisisResult,
    *,
    inflation_ceiling: float = 0.04,
    sustained_quarters: int = 4,
) -> dict[str, float | int | str | bool]:
    """Return diagnostics without imposing convergence or a terminal target."""

    if inflation_ceiling <= -1.0:
        raise ValueError("inflation ceiling must be greater than -100 percent")
    if sustained_quarters < 1:
        raise ValueError("sustained_quarters must be positive")
    path = result.quarterly
    terminal_lag = min(4, len(path) - 1)
    terminal_change = (
        float(
            path.iloc[-1]["debt_held_by_public_gdp_ratio"]
            - path.iloc[-1 - terminal_lag]["debt_held_by_public_gdp_ratio"]
        )
        if terminal_lag > 0
        else 0.0
    )
    terminal_inflation_change = (
        float(
            path.iloc[-1]["annual_inflation_rate"]
            - path.iloc[-1 - terminal_lag]["annual_inflation_rate"]
        )
        if terminal_lag > 0
        else 0.0
    )
    reference_inflation = result.reference_quarterly["annual_inflation_rate"].reset_index(drop=True)
    inflation_deviation = path["annual_inflation_rate"].reset_index(drop=True) - reference_inflation
    terminal_inflation_deviation_change = (
        float(inflation_deviation.iloc[-1] - inflation_deviation.iloc[-1 - terminal_lag])
        if terminal_lag > 0
        else 0.0
    )
    gross_issuance_gdp = (
        4.0 * path["gross_treasury_issuance_billions"] / path["nominal_gdp_billions_saar"]
    )
    first_breach = path.loc[path["annual_inflation_rate"] > inflation_ceiling, "quarter"]
    debt_yield_feedback = path.loc[
        path["debt_yield_long_adjustment_basis_points"] > 1e-9,
        "quarter",
    ]
    sustained = _first_sustained_breach(
        path["quarter"],
        path["annual_inflation_rate"],
        inflation_ceiling,
        sustained_quarters,
    )
    return {
        "scenario": result.scenario_name,
        "inflation_ceiling": inflation_ceiling,
        "sustained_breach_quarters": sustained_quarters,
        "first_inflation_ceiling_breach": "" if first_breach.empty else str(first_breach.iloc[0]),
        "first_sustained_inflation_ceiling_breach": sustained,
        "inflation_ceiling_breached": not first_breach.empty,
        "inflation_ceiling_breached_sustained": bool(sustained),
        "peak_inflation_rate": float(path["annual_inflation_rate"].max()),
        "peak_inflation_deviation_from_reference": float(inflation_deviation.max()),
        "terminal_inflation_rate": float(path.iloc[-1]["annual_inflation_rate"]),
        "terminal_inflation_deviation_from_reference": float(inflation_deviation.iloc[-1]),
        "terminal_four_quarter_inflation_change": terminal_inflation_change,
        "terminal_four_quarter_inflation_deviation_change": (terminal_inflation_deviation_change),
        "terminal_inflation_pressure_nonincreasing": (terminal_inflation_deviation_change <= 0.0),
        "peak_policy_rate": float(path["policy_rate_proxy"].max()),
        "peak_short_issuance_rate": float(path["short_issuance_rate"].max()),
        "terminal_debt_gdp_ratio": float(path.iloc[-1]["debt_held_by_public_gdp_ratio"]),
        "terminal_four_quarter_debt_gdp_change": terminal_change,
        "terminal_debt_gdp_nonincreasing": terminal_change <= 0.0,
        "minimum_output_gap": float(path["macro_feedback_output_gap"].min()),
        "maximum_output_gap": float(path["macro_feedback_output_gap"].max()),
        "peak_gross_issuance_gdp_ratio_annualized": float(gross_issuance_gdp.max()),
        "peak_interest_gdp_ratio_annualized": float(
            path["modeled_interest_gdp_ratio_annualized"].max()
        ),
        "peak_total_deficit_gdp_ratio_annualized": float(
            path["modeled_total_deficit_gdp_ratio_annualized"].max()
        ),
        "peak_incremental_cash_interest_billions": float(
            path["incremental_cash_interest_billions"].max()
        ),
        "cumulative_incremental_cash_interest_billions": float(
            path["incremental_cash_interest_billions"].sum()
        ),
        "peak_debt_gdp_gap_from_reference_percentage_points": float(
            path["debt_gdp_ratio_gap_from_reference_percentage_points"].max()
        ),
        "terminal_debt_gdp_gap_from_reference_percentage_points": float(
            path.iloc[-1]["debt_gdp_ratio_gap_from_reference_percentage_points"]
        ),
        "first_positive_debt_yield_feedback": (
            "" if debt_yield_feedback.empty else str(debt_yield_feedback.iloc[0])
        ),
        "peak_debt_yield_long_adjustment_basis_points": float(
            path["debt_yield_long_adjustment_basis_points"].max()
        ),
        "terminal_debt_yield_long_adjustment_basis_points": float(
            path.iloc[-1]["debt_yield_long_adjustment_basis_points"]
        ),
        "private_absorption_market_clearing_enabled": bool(
            path["private_absorption_market_clearing_enabled"].any()
        ),
        "peak_private_absorption_market_clearing_spread_basis_points": float(
            path["private_absorption_market_clearing_spread_basis_points"].max()
        ),
        "rate_bound_ever_binding": bool(path["rate_bound_binding"].any()),
    }


def run_sequential_crisis_simulation(
    initial_stock: DebtStock,
    reference_assumptions: pd.DataFrame,
    *,
    initial_nominal_gdp_billions_saar: float,
    initial_real_gdp_billions_chained_saar: float,
    policy_rule: PolicyRule | None = None,
    feedback_rule: SequentialFeedbackRule | None = None,
    debt_yield_feedback_rule: DebtYieldFeedbackRule | None = None,
    private_absorption_rule: PrivateAbsorptionRule | None = None,
    interest_income_rule: InterestIncomeRule | None = None,
    initial_inflation_rate: float | None = None,
    initial_output_gap: float = 0.0,
    treasury_premium_basis_points: PathInput = 0.0,
    private_credit_spread_basis_points: PathInput = 0.0,
    supply_inflation_pressure_rate: PathInput = 0.0,
    primary_balance_adjustment_gdp_share: PathInput = 0.0,
    issuance_strategy: IssuanceStrategy | None = None,
    scenario_name: str = "sequential_crisis",
    data_vintage: str = "unspecified",
) -> SequentialCrisisResult:
    """Advance debt, policy, output, and inflation in a causal quarterly loop.

    ``treasury_premium_basis_points`` is an initial or continuing market stress
    applied on top of the endogenous policy response. It does not prescribe
    subsequent Federal Reserve rate increases. ``debt_yield_feedback_rule``
    optionally maps the lagged deterioration relative to the no-shock debt path
    into additional Treasury yields. ``private_absorption_rule`` optionally
    solves for an additional common clearing spread and raises
    ``PrivateFinancingCapacityError`` when the supplied finite capacity cannot
    place the required issuance. A positive
    ``primary_balance_adjustment_gdp_share`` reduces the primary deficit by the
    stated share of contemporaneous annual-rate GDP. It enters the same fiscal
    demand and automatic-stabilizer loop as other primary-budget changes.
    """

    reference = validate_assumptions(reference_assumptions)
    policy = policy_rule or PolicyRule(regime=PolicyRegime.PRICE_STABILITY)
    feedback = feedback_rule or SequentialFeedbackRule()
    income = interest_income_rule or InterestIncomeRule()
    if policy.regime is not PolicyRegime.PRICE_STABILITY:
        raise ValueError("the first sequential slice supports the price-stability regime")
    if min(initial_nominal_gdp_billions_saar, initial_real_gdp_billions_chained_saar) <= 0.0:
        raise ValueError("initial GDP levels must be positive")
    if initial_output_gap <= -1.0:
        raise ValueError("initial output gap must be greater than -100 percent")

    index = reference.index
    premium_path = _numeric_path(
        index,
        treasury_premium_basis_points,
        "treasury_premium_basis_points",
    )
    private_spread_path = _numeric_path(
        index,
        private_credit_spread_basis_points,
        "private_credit_spread_basis_points",
    )
    supply_path = _numeric_path(
        index,
        supply_inflation_pressure_rate,
        "supply_inflation_pressure_rate",
    )
    primary_balance_adjustment_path = _numeric_path(
        index,
        primary_balance_adjustment_gdp_share,
        "primary_balance_adjustment_gdp_share",
    )
    if (premium_path < 0.0).any() or (private_spread_path < 0.0).any():
        raise ValueError("Treasury premiums and private credit spreads cannot be negative")
    if (primary_balance_adjustment_path < 0.0).any():
        raise ValueError("primary-balance adjustments cannot be negative")

    stress_stock = initial_stock.copy()
    reference_stock = initial_stock.copy()
    strategy = issuance_strategy or IssuanceStrategy()
    nominal_gdp = float(initial_nominal_gdp_billions_saar)
    real_gdp = float(initial_real_gdp_billions_chained_saar)
    reference_nominal_gdp = nominal_gdp
    reference_real_gdp = real_gdp
    potential_nominal_gdp = nominal_gdp
    current_inflation = (
        float(reference.iloc[0]["annual_inflation_rate"])
        if initial_inflation_rate is None
        else float(initial_inflation_rate)
    )
    if current_inflation <= -1.0:
        raise ValueError("initial inflation must be greater than -100 percent")
    prior_inflation_deviation_from_reference = current_inflation - float(
        reference.iloc[0]["annual_inflation_rate"]
    )
    current_output_gap = float(initial_output_gap)
    prior_output_gap = float(initial_output_gap)
    prior_policy_adjustment = 0.0

    stress_records: list[dict[str, float | int | str | bool | pd.Timestamp]] = []
    reference_records: list[dict[str, float | int | str | bool | pd.Timestamp]] = []
    output_gap_history: list[float] = []
    real_tightening_history: list[float] = []
    private_spread_history: list[float] = []
    primary_impulse_history: list[float] = []
    interest_demand_history: list[float] = []
    debt_gdp_gap_history: list[float] = []
    cumulative_stress_interest = 0.0
    cumulative_reference_interest = 0.0

    for position, (period, reference_row) in enumerate(reference.iterrows()):
        one_period_index = pd.PeriodIndex([period], freq="Q")
        reference_frame = pd.DataFrame([reference_row.to_dict()], index=one_period_index)
        reference_result = run_simulation(
            reference_stock,
            reference_frame,
            initial_nominal_gdp_billions_saar=reference_nominal_gdp,
            initial_real_gdp_billions_chained_saar=reference_real_gdp,
            issuance_strategy=strategy,
            scenario_name=f"{scenario_name}_reference",
            data_vintage=data_vintage,
        )
        reference_stock = reference_result.ending_stock
        reference_output = reference_result.quarterly.iloc[0].copy()
        reference_nominal_gdp = float(reference_output["nominal_gdp_billions_saar"])
        reference_real_gdp = float(reference_output["real_gdp_billions_chained_saar"])
        cumulative_reference_interest += float(
            reference_output["modeled_debt_interest_cost_billions"]
        )
        reference_output["cumulative_modeled_interest_billions"] = cumulative_reference_interest
        reference_output["short_issuance_rate"] = float(reference_row["short_issuance_rate"])
        reference_output["intermediate_issuance_rate"] = float(
            reference_row["intermediate_issuance_rate"]
        )
        reference_output["long_issuance_rate"] = float(reference_row["long_issuance_rate"])
        reference_output["tips_real_issuance_rate"] = float(
            reference_row["tips_real_issuance_rate"]
        )
        reference_records.append(reference_output.to_dict())

        reference_real_growth = float(reference_row["annual_real_gdp_growth_rate"])
        actual_real_growth = _actual_real_growth(
            reference_real_growth,
            current_output_gap,
            prior_output_gap,
        )
        potential_nominal_gdp, _ = advance_gdp(
            potential_nominal_gdp,
            real_gdp,
            reference_real_growth,
            current_inflation,
        )
        projected_nominal_gdp, _ = advance_gdp(
            nominal_gdp,
            real_gdp,
            actual_real_growth,
            current_inflation,
        )
        primary_scale = (
            projected_nominal_gdp / reference_nominal_gdp
            if feedback.primary_deficit_scales_with_nominal_gdp
            else 1.0
        )
        scaled_reference_primary = float(reference_row["primary_deficit_billions"]) * primary_scale
        automatic_stabilizer = (
            -feedback.automatic_stabilizer_semi_elasticity
            * current_output_gap
            * potential_nominal_gdp
            / 4.0
        )
        primary_balance_adjustment = (
            float(primary_balance_adjustment_path.loc[period])
            * projected_nominal_gdp
            / 4.0
        )
        primary_deficit = (
            scaled_reference_primary
            + automatic_stabilizer
            - primary_balance_adjustment
        )

        reference_inflation = float(reference_row["annual_inflation_rate"])
        inflation_gap = current_inflation - policy.inflation_target
        inflation_deviation_from_reference = current_inflation - reference_inflation
        desired_adjustment = (
            policy.inflation_response * inflation_deviation_from_reference
            + policy.output_gap_response * current_output_gap
        )
        policy_adjustment = (
            policy.reaction_smoothing * prior_policy_adjustment
            + (1.0 - policy.reaction_smoothing) * desired_adjustment
        )
        prior_policy_adjustment = policy_adjustment
        reference_short = float(reference_row["short_issuance_rate"])
        raw_policy_rate = reference_short + policy_adjustment
        policy_rate = min(max(raw_policy_rate, 0.0), policy.maximum_issuance_rate)
        premium = float(premium_path.loc[period]) / 10_000.0
        debt_signal_source = (
            position - debt_yield_feedback_rule.signal_lag_quarters
            if debt_yield_feedback_rule is not None
            else -1
        )
        debt_gdp_gap_signal = (
            debt_gdp_gap_history[debt_signal_source] if debt_signal_source >= 0 else 0.0
        )
        debt_yield_adjustments_basis_points = (
            debt_yield_feedback_rule.yield_adjustments_basis_points(debt_gdp_gap_signal)
            if debt_yield_feedback_rule is not None
            else {"short": 0.0, "intermediate": 0.0, "long": 0.0, "tips": 0.0}
        )
        debt_yield_adjustments = {
            maturity: basis_points / 10_000.0
            for maturity, basis_points in debt_yield_adjustments_basis_points.items()
        }
        raw_rates = {
            "short": policy_rate + premium + debt_yield_adjustments["short"],
            "intermediate": (
                float(reference_row["intermediate_issuance_rate"])
                + policy.intermediate_policy_pass_through * policy_adjustment
                + premium
                + debt_yield_adjustments["intermediate"]
            ),
            "long": (
                float(reference_row["long_issuance_rate"])
                + policy.long_policy_pass_through * policy_adjustment
                + premium
                + debt_yield_adjustments["long"]
            ),
            "tips": (
                float(reference_row["tips_real_issuance_rate"])
                + policy.tips_real_policy_pass_through * policy_adjustment
                + premium
                + debt_yield_adjustments["tips"]
            ),
        }
        market_clearing_spread_basis_points = 0.0
        private_absorption_state: dict[str, float | bool] = {
            "reference_scaled_issuance_billions": np.nan,
            "required_gross_issuance_billions": np.nan,
            "required_capacity_multiple": np.nan,
            "yield_gap_basis_points": np.nan,
            "capacity_multiple_at_actual_yield": np.nan,
            "capacity_billions_at_actual_yield": np.nan,
            "required_yield_gap_basis_points": np.nan,
            "finite_capacity_exceeded": False,
        }
        for _market_iteration in range(25):
            candidate_raw_rates = {
                maturity: rate + market_clearing_spread_basis_points / 10_000.0
                for maturity, rate in raw_rates.items()
            }
            actual_rates = {
                "short": min(
                    max(candidate_raw_rates["short"], 0.0),
                    policy.maximum_issuance_rate,
                ),
                "intermediate": min(
                    max(candidate_raw_rates["intermediate"], 0.0),
                    policy.maximum_issuance_rate,
                ),
                "long": min(
                    max(candidate_raw_rates["long"], 0.0),
                    policy.maximum_issuance_rate,
                ),
                "tips": min(
                    max(candidate_raw_rates["tips"], -0.99),
                    policy.maximum_issuance_rate,
                ),
            }
            rate_bound_binding = not np.isclose(raw_policy_rate, policy_rate) or any(
                not np.isclose(candidate_raw_rates[key], actual_rates[key])
                for key in candidate_raw_rates
            )

            stress_row = reference_row.copy()
            stress_row["annual_real_gdp_growth_rate"] = actual_real_growth
            stress_row["annual_inflation_rate"] = current_inflation
            stress_row["annual_tips_reference_inflation_rate"] = float(
                reference_row["annual_tips_reference_inflation_rate"]
            ) + (0.0 if position == 0 else prior_inflation_deviation_from_reference)
            stress_row["primary_deficit_billions"] = primary_deficit
            stress_row["short_issuance_rate"] = actual_rates["short"]
            stress_row["intermediate_issuance_rate"] = actual_rates["intermediate"]
            stress_row["long_issuance_rate"] = actual_rates["long"]
            stress_row["tips_real_issuance_rate"] = actual_rates["tips"]
            stress_frame = pd.DataFrame([stress_row.to_dict()], index=one_period_index)
            stress_result = run_simulation(
                stress_stock,
                stress_frame,
                initial_nominal_gdp_billions_saar=nominal_gdp,
                initial_real_gdp_billions_chained_saar=real_gdp,
                issuance_strategy=strategy,
                scenario_name=scenario_name,
                data_vintage=data_vintage,
            )
            stress_output = stress_result.quarterly.iloc[0].copy()
            stress_output["short_issuance_rate"] = actual_rates["short"]
            stress_output["intermediate_issuance_rate"] = actual_rates["intermediate"]
            stress_output["long_issuance_rate"] = actual_rates["long"]
            stress_output["tips_real_issuance_rate"] = actual_rates["tips"]
            if private_absorption_rule is None:
                break

            private_absorption_state = _private_absorption_state(
                stress_output,
                reference_output,
                private_absorption_rule,
            )
            reference_scaled = float(
                private_absorption_state["reference_scaled_issuance_billions"]
            )
            if bool(private_absorption_state["finite_capacity_exceeded"]):
                raise PrivateFinancingCapacityError(
                    quarter=str(period),
                    required_capacity_multiple=float(
                        private_absorption_state["required_capacity_multiple"]
                    ),
                    maximum_capacity_multiple=(
                        private_absorption_rule.maximum_capacity_multiple
                    ),
                    required_gross_issuance_billions=float(
                        private_absorption_state["required_gross_issuance_billions"]
                    ),
                    maximum_capacity_billions=(
                        reference_scaled * private_absorption_rule.maximum_capacity_multiple
                    ),
                )
            additional_spread = max(
                float(private_absorption_state["required_yield_gap_basis_points"])
                - float(private_absorption_state["yield_gap_basis_points"]),
                0.0,
            )
            if additional_spread <= 1e-6:
                break
            if not np.isfinite(additional_spread):
                raise PrivateFinancingCapacityError(
                    quarter=str(period),
                    required_capacity_multiple=float(
                        private_absorption_state["required_capacity_multiple"]
                    ),
                    maximum_capacity_multiple=(
                        private_absorption_rule.maximum_capacity_multiple
                    ),
                    required_gross_issuance_billions=float(
                        private_absorption_state["required_gross_issuance_billions"]
                    ),
                    maximum_capacity_billions=(
                        reference_scaled * private_absorption_rule.maximum_capacity_multiple
                    ),
                    reason="zero_yield_sensitivity",
                )
            market_clearing_spread_basis_points += additional_spread
        else:
            raise RuntimeError(f"private-absorption clearing spread did not converge in {period}")

        stress_stock = stress_result.ending_stock
        nominal_gdp = float(stress_output["nominal_gdp_billions_saar"])
        real_gdp = float(stress_output["real_gdp_billions_chained_saar"])
        cumulative_stress_interest += float(stress_output["modeled_debt_interest_cost_billions"])
        stress_output["cumulative_modeled_interest_billions"] = cumulative_stress_interest

        stress_cash_interest = _cash_interest(stress_output)
        reference_cash_interest = _cash_interest(reference_output)
        nominal_incremental_cash_interest = stress_cash_interest - reference_cash_interest
        stress_cash_interest_share = annualized_flow_gdp_share(
            stress_cash_interest,
            nominal_gdp,
        )
        reference_cash_interest_share = annualized_flow_gdp_share(
            reference_cash_interest,
            reference_nominal_gdp,
        )
        incremental_cash_interest_share = stress_cash_interest_share - reference_cash_interest_share
        # Express the real, GDP-share difference in current scenario dollars.
        # A raw nominal subtraction would mistake a higher scenario price level
        # for additional real purchasing power.
        incremental_cash_interest = incremental_cash_interest_share * nominal_gdp / 4.0
        interest_demand = income.domestic_demand_billions(incremental_cash_interest)
        interest_demand_share = annualized_flow_gdp_share(interest_demand, nominal_gdp)
        primary_impulse = primary_deficit - scaled_reference_primary
        primary_impulse_share = annualized_flow_gdp_share(primary_impulse, nominal_gdp)
        scenario_real_rate = policy_rate - current_inflation
        reference_real_rate = reference_short - float(reference_row["annual_inflation_rate"])
        real_policy_tightening = scenario_real_rate - reference_real_rate

        stress_output["reference_primary_deficit_scaled_billions"] = scaled_reference_primary
        stress_output["automatic_stabilizer_primary_deficit_billions"] = automatic_stabilizer
        stress_output["primary_balance_adjustment_gdp_share"] = float(
            primary_balance_adjustment_path.loc[period]
        )
        stress_output["primary_balance_adjustment_billions"] = primary_balance_adjustment
        stress_output["macro_feedback_output_gap"] = current_output_gap
        stress_output["policy_inflation_gap_to_target"] = inflation_gap
        stress_output["policy_inflation_deviation_from_reference"] = (
            inflation_deviation_from_reference
        )
        stress_output["policy_rate_adjustment"] = policy_adjustment
        stress_output["policy_rate_proxy"] = policy_rate
        stress_output["real_policy_tightening_rate_gap"] = real_policy_tightening
        stress_output["treasury_premium_basis_points"] = float(premium_path.loc[period])
        debt_gdp_gap = 100.0 * float(
            stress_output["debt_held_by_public_gdp_ratio"]
            - reference_output["debt_held_by_public_gdp_ratio"]
        )
        stress_output["debt_gdp_ratio_gap_from_reference_percentage_points"] = debt_gdp_gap
        stress_output["debt_gdp_ratio_feedback_signal_percentage_points"] = debt_gdp_gap_signal
        stress_output["debt_yield_feedback_enabled"] = debt_yield_feedback_rule is not None
        stress_output["debt_yield_short_adjustment_basis_points"] = (
            debt_yield_adjustments_basis_points["short"]
        )
        stress_output["debt_yield_intermediate_adjustment_basis_points"] = (
            debt_yield_adjustments_basis_points["intermediate"]
        )
        stress_output["debt_yield_long_adjustment_basis_points"] = (
            debt_yield_adjustments_basis_points["long"]
        )
        stress_output["debt_yield_tips_real_adjustment_basis_points"] = (
            debt_yield_adjustments_basis_points["tips"]
        )
        stress_output["private_credit_spread_basis_points"] = float(private_spread_path.loc[period])
        stress_output["short_issuance_rate"] = actual_rates["short"]
        stress_output["intermediate_issuance_rate"] = actual_rates["intermediate"]
        stress_output["long_issuance_rate"] = actual_rates["long"]
        stress_output["tips_real_issuance_rate"] = actual_rates["tips"]
        stress_output["raw_short_issuance_rate"] = candidate_raw_rates["short"]
        stress_output["raw_intermediate_issuance_rate"] = candidate_raw_rates["intermediate"]
        stress_output["raw_long_issuance_rate"] = candidate_raw_rates["long"]
        stress_output["rate_bound_binding"] = rate_bound_binding
        stress_output["private_absorption_market_clearing_enabled"] = (
            private_absorption_rule is not None
        )
        stress_output["private_absorption_market_clearing_iterations"] = _market_iteration + 1
        stress_output["private_absorption_market_clearing_spread_basis_points"] = (
            market_clearing_spread_basis_points
        )
        stress_output["private_absorption_required_capacity_multiple"] = (
            private_absorption_state["required_capacity_multiple"]
        )
        stress_output["private_absorption_capacity_multiple_at_clearing_yield"] = (
            private_absorption_state["capacity_multiple_at_actual_yield"]
        )
        stress_output["private_absorption_required_yield_gap_basis_points"] = (
            private_absorption_state["required_yield_gap_basis_points"]
        )
        stress_output["reference_cash_interest_billions"] = reference_cash_interest
        stress_output["stress_cash_interest_billions"] = stress_cash_interest
        stress_output["nominal_incremental_cash_interest_billions"] = (
            nominal_incremental_cash_interest
        )
        stress_output["incremental_cash_interest_billions"] = incremental_cash_interest
        stress_output["incremental_cash_interest_gdp_ratio_annualized"] = (
            incremental_cash_interest_share
        )
        stress_output["interest_income_domestic_demand_fraction"] = income.domestic_demand_fraction
        stress_output["incremental_interest_domestic_demand_billions"] = interest_demand
        stress_output["incremental_interest_demand_gdp_ratio_annualized"] = interest_demand_share
        stress_output["incremental_primary_impulse_gdp_ratio_annualized"] = primary_impulse_share
        stress_output["supply_inflation_pressure_rate"] = float(supply_path.loc[period])
        stress_output["terminal_debt_target_imposed"] = False
        stress_records.append(stress_output.to_dict())

        output_gap_history.append(current_output_gap)
        real_tightening_history.append(real_policy_tightening)
        private_spread_history.append(float(private_spread_path.loc[period]) / 10_000.0)
        primary_impulse_history.append(primary_impulse_share)
        interest_demand_history.append(interest_demand_share)
        debt_gdp_gap_history.append(debt_gdp_gap)

        next_position = position + 1
        if next_position < len(reference):
            policy_source = next_position - feedback.policy_effect_lag_quarters
            fiscal_source = next_position - feedback.fiscal_effect_lag_quarters
            monetary_effect = (
                feedback.policy_tightening_output_semi_elasticity
                * real_tightening_history[policy_source]
                if policy_source >= 0
                else 0.0
            )
            private_credit_effect = (
                feedback.private_credit_spread_output_semi_elasticity
                * private_spread_history[policy_source]
                if policy_source >= 0
                else 0.0
            )
            primary_effect = (
                feedback.primary_deficit_output_multiplier * primary_impulse_history[fiscal_source]
                if fiscal_source >= 0
                else 0.0
            )
            interest_effect = (
                feedback.interest_income_output_multiplier * interest_demand_history[fiscal_source]
                if fiscal_source >= 0
                else 0.0
            )
            next_output_gap = (
                feedback.output_gap_persistence * current_output_gap
                - monetary_effect
                - private_credit_effect
                + primary_effect
                + interest_effect
            )
            inflation_source = next_position - feedback.inflation_gap_lag_quarters
            lagged_output_gap = (
                output_gap_history[inflation_source]
                if inflation_source >= 0
                else initial_output_gap
            )
            next_reference_inflation = float(reference.iloc[next_position]["annual_inflation_rate"])
            next_inflation = (
                next_reference_inflation
                + feedback.inflation_persistence * inflation_deviation_from_reference
                + feedback.inflation_output_gap_sensitivity * lagged_output_gap
                + float(supply_path.iloc[next_position])
            )
            if next_inflation <= -1.0:
                raise ValueError("inflation reached the model boundary at -100 percent")
            if next_output_gap <= -1.0:
                raise ValueError("output gap reached the model boundary at -100 percent")
            prior_output_gap = current_output_gap
            current_output_gap = next_output_gap
            prior_inflation_deviation_from_reference = inflation_deviation_from_reference
            current_inflation = next_inflation

    quarterly = pd.DataFrame(stress_records).reset_index(drop=True)
    reference_quarterly = pd.DataFrame(reference_records).reset_index(drop=True)
    return SequentialCrisisResult(
        quarterly=quarterly,
        reference_quarterly=reference_quarterly,
        ending_stock=stress_stock,
        reference_ending_stock=reference_stock,
        scenario_name=scenario_name,
        data_vintage=data_vintage,
    )
